x=factor(c('Male','Female','Male'))
x
x=factor(c("yes","no","no"),levels=c("yes","no"))
x
x1=factor(c('low','medium','high'),ordered=T)
x1
x2=factor(c('low','medium','high'),ordered=T,levels=c("low","medium","high"))
x2
g=c('M','F','F','M')
g
h=factor(g)
h
m=c('jan','feb','may')
m=rep(m,2)

month.abb[1:12]
m1=factor(m)
m1
m2=factor(m,levels=c('Jan','Feb','May'),ordered=T)
m2
m3=c(m,'xyz')
m3
m4=c(m,'apr')
m4
gender=c(1,2,1,1,2)
fgender=factor(gender)
fgender
fgender=factor(gender,levels=c(1,2),labels=c('M','F'))
fgender
status=c(1,2,3,4)
fstatus=factor(status)
fstatus
fstatus=factor(status,levels=c(1,2,3,4),labels=c("bad","average","good","excellent"))
fstatus
levels(fstatus)
levels(fstatus)=c(levels(fstatus),'outstanding')
levels(fstatus)
fstatus
fstatus[5]='outstanding'
fstatus
summary(fstatus)
table(fstatus)
fstatus[c(6,7)]=c('good','bad')
fstatus
clspos=c(1,2,3,2,4,1,3)
class(clspos)
levels(clspos)
summary(clspos)
mode(clspos)
fclspos=factor(clspos)
fclspos
summary(fclspos)
levels(fclspos)
fclspos2=factor(clspos,levels=c(1,2,3,4,5),ordered=T,labels=c('FIRST','SECOND','THIRD','FOURTH','FIFTH'))
fclspos2
summary(fclspos2)
levels(fclspos2)
fclspos3=factor(fclspos2,levels(fclspos2)[c(5,4,3,2,1)])
fclspos3
rev(levels(fclspos2))
fclspos2
fclspos4=factor(fclspos2,levels=rev(levels(fclspos2)))
fclspos4
                                                          